### ISSUE TITLE
Restore Coder

### ISSUE THREAD

**Issue by bennytheshap** [LaboratoryForPlayfulComputation/blockytalky#32]

**Comment by mpahrens** [comment]
Almost done with this.
TODO: 
- fix straggling Brick/GrovePi deps
- Add link to "more options" dropdown

**Comment by mpahrens** [comment]
Ok, the brickpi dep thing was just in the easy_setup version of BrickPi. The "cached" version I am bundling as a redistributable in priv/hw_apis still works fine. I left an issue with John + team, but it is not urgent as I can work around it with the v1.0.0 brickpi rather than the latest master

https://github.com/DexterInd/BrickPi_Python/issues/59

**Comment by mpahrens** [comment]
After being unblocked by that weird erlang <R17 bug, I can make a new image to accompany v0.4 this week so we can close this out

**Comment by mpahrens** [comment]
New image was uploaded and published in a message on basecamp
